services:
  app:
    build: 
      context: .
      args:
        ENDPOINTS_PATH: ${ENDPOINTS_PATH}
    environment:
      ENDPOINTS_PATH: ${ENDPOINTS_PATH}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ruby app/main.rb ${ENDPOINTS_PATH}