services:
  app:
    build: 
      context: .
      args:
        ENDPOINTS_PATH: ${ENDPOINTS_PATH}
    depends_on:
      - test_api
    environment:
      ENDPOINTS_PATH: ${ENDPOINTS_PATH}
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: ruby app/main.rb ${ENDPOINTS_PATH}

  test_api:
    build:
      context: .
      dockerfile: Dockerfile.test_api
    working_dir: /app
    ports:
      - "4567:4567"
