FROM ruby:3.2-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl && \
    rm -rf /var/lib/apt/lists/*

COPY test_api/Gemfile ../Gemfile.lock ./
RUN bundle install

COPY test_api .

EXPOSE 4567
CMD ["bundle", "exec", "ruby", "test_api.rb", "-o", "0.0.0.0", "-p", "4567"]
